# Generated by Django 4.2.7 on 2023-11-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='img_marca',
            field=models.ImageField(upload_to='static/marcas/'),
        ),
    ]
