# Generated by Django 4.2.7 on 2023-11-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0002_fornecedor_telefone_fornecedor_telefone_zap'),
        ('marcas', '0002_alter_marca_img_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='fornecedores',
            field=models.ManyToManyField(related_name='marcas', to='fornecedores.fornecedor'),
        ),
    ]
