# Generated by Django 4.2.7 on 2023-12-22 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0003_alter_fornecedor_cnpj'),
        ('marcas', '0003_marca_fornecedores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='fornecedores',
        ),
        migrations.AddField(
            model_name='marca',
            name='fornecedores',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fornecedores.fornecedor', verbose_name='Fornecedor'),
            preserve_default=False,
        ),
    ]
