# Generated by Django 4.2.7 on 2024-01-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcas', '0004_remove_marca_fornecedores_marca_fornecedores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='img_marca',
            field=models.ImageField(upload_to='media/marcas/'),
        ),
    ]
