# Generated by Django 4.2.7 on 2024-01-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcas', '0005_alter_marca_img_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='img_marca',
            field=models.ImageField(upload_to='marcas/'),
        ),
    ]
