# Generated by Django 4.2.7 on 2023-12-22 23:35

import apps.clientes.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='lucasm676@gmail.com', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=apps.clientes.models.BrazilianCellPhoneField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(code='telefone_invalido', message='Insira um telefone válido', regex='^0?\\d{2}\\s?9\\d{4}\\s?-?\\d{4}$')], verbose_name='Celular'),
        ),
    ]
