# Generated by Django 4.2.7 on 2023-11-17 17:21

import apps.motoboys.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motoboys', '0002_rename_motoboys_motoboy'),
    ]

    operations = [
        migrations.AddField(
            model_name='motoboy',
            name='placa',
            field=apps.motoboys.models.BrazilianPlates(default='qsh2i24', max_length=11, validators=[django.core.validators.RegexValidator(code='placa_invalida', message='Insira uma placa válida.', regex='^([A-Z]{3}[0-9][A-Z][0-9]{3})|([A-Z]{3}[0-9]{4})$')]),
            preserve_default=False,
        ),
    ]
