# Generated by Django 4.2.7 on 2023-11-18 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='cod_barras',
        ),
    ]
