# Generated by Django 4.2.7 on 2023-11-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_remove_produto_cod_barras'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cod_barras',
            field=models.ImageField(default=1, upload_to='static/produtos/cod_barras'),
            preserve_default=False,
        ),
    ]
