# Generated by Django 4.2.7 on 2023-12-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_cod_barras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='cod_barras',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='qtd_tam_g',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='qtd_tam_gg',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='qtd_tam_m',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='qtd_tam_p',
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('camisas_camisetas_masculinas', 'Camisas e Camisetas Masculinas'), ('calcas_masculinas', 'Calças Masculinas'), ('bermudas_shorts_masculinos', 'Bermudas e Shorts Masculinos'), ('blazers_ternos_masculinos', 'Blazers e Ternos Masculinos'), ('jaquetas_casacos_masculinos', 'Jaquetas e Casacos Masculinos'), ('roupas_esportivas_masculinas', 'Roupas Esportivas Masculinas'), ('roupas_intimas_masculinas', 'Roupas Íntimas Masculinas'), ('blusas_camisetas_femininas', 'Blusas e Camisetas Femininas'), ('vestidos_saias_femininas', 'Vestidos e Saias Femininas'), ('calcas_femininas', 'Calças Femininas'), ('shorts_bermudas_femininas', 'Shorts e Bermudas Femininas'), ('blazers_tailleurs_femininos', 'Blazers e Tailleurs Femininos'), ('jaquetas_casacos_femininos', 'Jaquetas e Casacos Femininos'), ('roupas_esportivas_femininas', 'Roupas Esportivas Femininas'), ('roupas_intimas_femininas', 'Roupas Íntimas Femininas'), ('roupas_bebes', 'Roupas para Bebês'), ('roupas_meninos', 'Roupas para Meninos'), ('roupas_meninas', 'Roupas para Meninas'), ('uniformes_escolares', 'Uniformes Escolares'), ('bolsas_mochilas', 'Bolsas e Mochilas'), ('cintos', 'Cintos'), ('chapeus_bones', 'Chapéus e Bonés'), ('luvas_cachecois', 'Luvas e Cachecóis'), ('joias_bijuterias', 'Joias e Bijuterias')], default='camisas_camisetas_masculinas', max_length=50),
        ),
    ]
