# Generated by Django 4.2.7 on 2023-11-15 12:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_produto_img_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='cod_barras',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
