# Generated by Django 4.2.7 on 2023-12-17 17:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_remove_produto_cod_barras_remove_produto_qtd_tam_g_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_tam_p', models.PositiveIntegerField()),
                ('qtd_tam_m', models.PositiveIntegerField()),
                ('qtd_tam_g', models.PositiveIntegerField()),
                ('qtd_tam_gg', models.PositiveIntegerField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
        ),
    ]
