# Generated by Django 4.2.7 on 2023-12-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_produto_preco_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='qtd_tam_g',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='qtd_tam_gg',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='qtd_tam_m',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='qtd_tam_p',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Estoque',
        ),
    ]
