# Generated by Django 4.2.7 on 2024-01-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_produto_qtd_tam_g_produto_qtd_tam_gg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='img_produto',
            field=models.ImageField(upload_to='static/produtos'),
        ),
    ]
