# Generated by Django 4.2.7 on 2024-01-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_alter_produto_img_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='img_produto',
            field=models.ImageField(upload_to='media/produtos'),
        ),
    ]
