# Generated by Django 4.2.7 on 2024-01-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_alter_produto_img_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='etiqueta',
            field=models.ImageField(blank=True, upload_to='etiquetas/'),
        ),
    ]
