# Generated by Django 4.2.7 on 2023-11-17 16:53

import apps.fornecedores.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='telefone',
            field=apps.fornecedores.models.BrazilianCellPhoneField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(code='telefone_invalido', message='Insira um telefone válido', regex='^9[0-9]{10}$')]),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='telefone_zap',
            field=models.BooleanField(default=False),
        ),
    ]
