# Generated by Django 4.2.7 on 2023-12-22 23:25

from django.db import migrations
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0002_fornecedor_telefone_fornecedor_telefone_zap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=localflavor.br.models.BRCNPJField(max_length=18, unique=True),
        ),
    ]
