# Generated by Django 4.2.7 on 2023-11-13 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendedores',
            new_name='Vendedor',
        ),
    ]
