# Generated by Django 4.2.7 on 2023-12-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0002_rename_vendedores_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='foto',
            field=models.ImageField(upload_to='static/vendedores/'),
        ),
    ]
