# Generated by Django 4.2.7 on 2023-12-22 23:25

from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0003_alter_vendedor_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='cpf',
            field=localflavor.br.models.BRCPFField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
