# Generated by Django 4.2.7 on 2024-01-09 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0004_alter_vendedor_cpf_alter_vendedor_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendedor',
            options={'permissions': [('vendedor_permission', 'Pode acessar funções de vendedor')]},
        ),
    ]
