# Generated by Django 4.2.7 on 2024-01-09 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0006_vendedor_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='id_usuario',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
