# Generated by Django 4.2.7 on 2024-01-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0008_alter_vendedor_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='foto',
            field=models.ImageField(upload_to='vendedores/'),
        ),
    ]
