# Generated by Django 4.2.7 on 2024-01-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrinho',
            name='tamanho',
            field=models.CharField(choices=[('P', 'p'), ('M', 'm'), ('G', 'g'), ('GG', 'gg')], default='P', max_length=2),
            preserve_default=False,
        ),
    ]
